#!/usr/bin/env python
import tweepy

auth = tweepy.OAuthHandler('xAjC0FrTb6iZitG57zHIbDbGf', 'A3zzB9uIzCfcBEjFANpG0G3S3lONqfU0BBjKPByn2aNKEWSC0K')
auth.set_access_token('1287883285599866880-tE8Dlx4BwJ5Tjg7gbNff7cMaNoA9vv', 'wLzuMRaa3Pkl17dC1pxyYktqw8Hc22HKtqJ8SQ1Q3IDyS')

api = tweepy.API(auth)

tweet = input("Twitter for iPhone? Twitter for Android? Ha I have Twitter for Let Shuhua Say Fuck")

api.update_status(status = (tweet))
print('Done!')
